#! /bin/bash

nowplaying() {
    SONG="$(
    if ps -C cmus > /dev/null; then
        artist=$(cmus-remote -Q | grep '^tag artist' | sed '/^tag artistsort/d'  | awk '{gsub("tag artist ", "");print}' )
        title=$(cmus-remote -Q  | grep '^tag title' | awk '{gsub("tag title ", "");print}')
        echo "${artist} - ${title}";
    else
        echo
    fi
)"

echo $SONG

}

nxt="%{A:cmus-remote -n:} >> %{A}"
prv="%{A:cmus-remote -r:} << %{A}"
ply="%{A:cmus-remote -u:} X %{A}"

bw=600
bh=20
bx=20
by=20

bg="#e8e8ea"
fg="#545855"

fnt="-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*"

opt="-g ${bw}x${bh}+${bx}+${by} -B ${bg} -F ${fg}"

while :; do
    echo "   $(nowplaying) %{r}$prv $ply $nxt  " 
    sleep 1
done | lemonbar -d -p $opt -f "$fnt" | sh 
