#! /bin/bash
#
# 2016 : jsphsnkr
# simple script to snap window to quantised (20x20) center of screen

# get current window id, borderwidth, and dimensions
WID=$1
BW=$(wattr b $WID)
WW=$(wattr w $WID)
WH=$(wattr h $WID)

# get size of root window
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

center()
{
        wtp $(((SW - WW)/40  *20)) $(((SH -WH)/40 *20)) $WW $WH $WID
}

center
