#!/bin/sh

. grabcolours.sh

sw=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
sh=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

w=$sw
h=16
xoff=$((sw/2 - w/2))
yoff=$((sh - h))

dmenu_run -b -fn "$fnt" -nb "#$bg" -nf "#$fg" -sb "#$bg" -sf "#$red" -x $xoff -y $yoff -w $w -h $h
