#!/bin/sh

. grabcolours.sh

sw=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
sh=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

w=$((sw - 160))
h=20
xoff=0
yoff=0

dmenu_run -fn $fnt -nb "#$bg" -nf "#$fg" -sb "#$bg" -sf "#$red" -x $xoff -y $yoff -w $w -h $h
