#!/bin/bash
#
# szyslak - simple bartender
# inspired by tudurom's statusbar script, thanks!
#

# create status fifo
FIFO_PATH=/tmp/status.fifo
test -e "$FIFO_PATH" && rm "$FIFO_PATH"
mkfifo "$FIFO_PATH"

#
# get status elements
#

# clock
while :; do
	echo "C$(date '+%a %H:%M')"
	#echo "C$(brclock)"
	sleep 30s
done > "$FIFO_PATH" &

# battery
while :; do
	lvl=$(cat /sys/class/power_supply/BAT1/capacity)
	stat=$(cat /sys/class/power_supply/BAT1/status)

	buf="$lvl"
	if [ $stat = "Full" ]
	then
		buf="= $buf ="
	elif [ $stat = "Discharging" ]
	then
		buf="- $buf -"
	elif [ $stat = "Charging" ]
	then
		buf="+ $buf +"
	fi

	echo "B$buf"
	sleep 30s
done > "$FIFO_PATH" &

# music
while :; do
	echo "M$(murphy)"
	sleep 1s
done > "$FIFO_PATH" &

# parse and display fifo contents
cat "$FIFO_PATH" | while read -r line; do
	case $line in
		C*)
			clock="${line#?}"
			;;
		B*)
			battery="${line#?}"
			;;
		M*)
			music="${line#?}"
			;;
	esac

	xsetroot -name " $music  $battery  $clock "
done 
