#!/bin/sh
#
# statusline generator for dwm
#

clock() {
    date '+%a %H:%M'
}

battery() {
    bat=$(cat /sys/class/power_supply/BAT1/capacity)
    bats=$(cat /sys/class/power_supply/BAT1/status)
    batbuf=""
    if [ $bat -le 10 ] 
    then
        batbuf="[    ]"
    elif [ $bat -gt 10 ] && [ $bat -le 25 ] 
    then
        batbuf="[=   ]"
    elif [ $bat -gt 25 ] && [ $bat -le 50 ] 
    then
        batbuf="[==  ]"
    elif [ $bat -gt 50 ] && [ $bat -le 75 ] 
    then
        batbuf="[=== ]"
    elif [ $bat -gt 75 ] && [ $bat -le 100 ] 
    then
        batbuf="[====]"
    fi
    
	batbuf="$bat"

    if [ $bats = "Full" ] 
    then
        batbuf="= $batbuf ="
    elif [ $bats = "Discharging" ] 
    then
        batbuf="- $batbuf -"
    elif [ $bats = "Charging" ] 
    then
        batbuf="+ $batbuf +"
    fi

    echo "$batbuf"
    

}

volume() {
    vol=$(amixer -M get Master | awk -F"[][]" '/dB/ { print $2 }')
    echo "$vol"
}


nowplaying(){
    murphy
}



while :; do
	buf=" $(nowplaying) | $(battery) | $(clock) "
    xsetroot -name "${buf}"
    sleep 2s
done
