#!/usr/bin/env python

import sys
from PIL import Image

im = Image.open("/home/spinks/Pictures/wallpaper/pxl_rocktower.jpg")

def dom_colour(image):
    w, h = image.size
    pxls = image.getcolors(w*h)

    dom_pxl = pxls[0]

    for count, colour in pxls:
        if count > dom_pxl[0]:
            dom_pxl = (count, colour)

    #compare("Most Common", image, dom_pxl[1])

    return dom_pxl

print dom_colour(im)


