#!/bin/bash

# define colors for color-echo
red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
bprp="\e[35;1m"
rst="\e[0m"

color-echo()
{  # print with colors
  echo -e " $blu$1: $rst$2"
}

print-kernel()
{
  color-echo 'KN' "$(uname -r)"
}

print-shell() {
color-echo 'SH' $SHELL
}

print-packages()
{
  packages=$(pacman -Qqs | wc -l)
  color-echo 'PK' "$packages"
}

print-wm()
{
    color-echo 'WM' "wmutils"
}

print-distro()
{
  [[ -e /etc/os-release ]] && source /etc/os-release
  if [[ -n "$PRETTY_NAME" ]]; then
    color-echo 'OS' "$PRETTY_NAME"
  else
    color-echo 'OS' "not found"
  fi
}

#echo -e "\n  $bprp$USER@$HOSTNAME$rst\n"
echo -en "\n"
echo -en "     " && print-distro
echo -en "     " && print-kernel
echo -en "     " && print-shell
echo -en "     " && print-packages
echo -en "     " && print-wm
echo -en "\n"
echo -en "          ${blu}███${red}███${grn}███" 
echo -en "\n"
