#!/bin/sh
#
# homer - managing power levels in sector 7G
#

lvl=10

while :; do
    bat=$(cat /sys/class/power_supply/BAT1/capacity)
    test ${bat} -le ${lvl} && notify-send "Battery low!"
    sleep 30s
done
