#! /bin/bash

screenw=$(xrandr -q | grep Screen | awk '{ print $8 }') 
screenh=$(xrandr -q | grep Screen | awk '{ print $10 }' | cut -d ',' -f1)

panelh=16
panelw=$screenw
xoff=$((screenw /2 - panelw /2))
#xoff=20

if [ $# -ne 1 ]; then
    hicol=#cb6077
else
    hicol=$1
fi

#bspc config top_padding $panelh

#echo "" | lemonbar -p -g $((panelw))x$((panelh))+$((xoff))+0 -B "$hicol" &

sleep 1s

statusline | lemonbar -d -g $((panelw))x$((panelh))+$((xoff))+0 -B "#000000" -F "#ffffff" -f "-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*"
