#!/bin/sh
#
# volume management (ALSA Master channel)
# thanks, z3bra!

test "$1" = "-h" && echo "usage `basename $0` [+|-|!]" && exit 0

level() {
    amixer get Master | sed -n 's/^.*\[\([0-9]\+%\).*$/\1/p' | uniq
}

state() {
    amixer get Master | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq
}

test $# -eq 0 && echo "`level` `state`" && exit 0

case $1 in
    +) amixer set Master 3dB+ >/dev/null ;;
    -) amixer set Master 3dB- >/dev/null ;;
    !) amixer set Master 0% >/dev/null ;;
    state|level) $1;;
    *)    amixer set Master $1 >/dev/null;;
esac
