#!/bin/sh

. grabcolours.sh

# duration
dur=3

# geometry
sw=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
sh=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)
bw=$((sw - 200))
bh=14
bx=$((sw/2 - bw/2))
by=$((sh - bh))

# arrange as lemonbar arguments
opt="-g ${bw}x${bh}+${bx}+${by} -B "#${bg}" -F "#${fg}""

# create the popup
(echo "%{c}$@"; sleep ${dur}) | lemonbar -d $opt -f $fnt
