#! /bin/bash

# duration
dur=3

# geometry
bx=20
by=20
bw=200
bh=40

# colours
bg="#a7a7a7"
fg="#1e1e1e"

# font
fnt="-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*"

# arrange as lemonbar arguments
opt="-g ${bw}x${bh}+${bx}+${by} -B ${bg} -F ${fg} -f ${fnt}"

# create the popup
(echo "%{c}$@"; sleep ${dur}) | lemonbar -d ${opt} 

