#!/bin/sh

. grabcolours.sh

# duration
dur=3

# geometry
sw=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
sh=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)
bw=256
bh=30
bx=$((sw - bw - 20))
by=20

# arrange as lemonbar arguments
opt="-g ${bw}x${bh}+${bx}+${by} -B #${bg} -F #${fg}" 

# create the popup
(echo "%{c}$@"; sleep ${dur}) |  lemonbar -d $opt -f $fnt
