#!/bin/sh
#

plyr=mpv

fcur=$HOME/.radio_cur

stationlist=$HOME/dotfiles/radio

if [ "$1" = "stop" ]; then
	pkill mpv 
	echo "none" > $fcur
elif [ "$1" = "list" ]; then
	echo $(cat $stationlist | cut -d' ' -f1 | sort) | tr " " "\n"
elif [ -z $1 ]; then
	exit
else
	url=$(cat $stationlist | grep -w $1 | cut -d' ' -f2)
	pkill $plyr 
	$plyr "$url" &>/dev/null &
	echo "$1" > $fcur
fi
