#!/bin/sh
#

plyr=mpv

fcur=$HOME/.radio_cur

stationlist=$HOME/dotfiles/radio

if [ "$1" = "stop" ]; then
	pkill mpv 
	echo "none" > $fcur
elif [ -z $1 ]; then
	exit
else
	url=$(cat $stationlist | grep -w $1 | cut -d' ' -f2)
	pkill $plyr 
	$plyr "$url" &
	echo "$1" > $fcur
fi
