#!/bin/sh
#
# razz - simple radio tuner 
#

plyr=mpv

fcur=$HOME/.radio_cur

# where is the list of streams?
stationlist=$HOME/dotfiles/radio

# load colour defs
#. grabcolours.sh

fnt="hack:size=9:antialias=true:hinting=true"
bg="282828"
fg="fbf1c7"
lo="928374"

dmenu_cmd="dmenu -p $(cat $fcur) -fn $fnt -nb #$bg -nf #$lo -sb #$bg -sf #$fg"

stn=$(cat $stationlist | cut -d' ' -f1 | sort | $dmenu_cmd)

if [ "$stn" = "stop" ]; then
	pkill $plyr
	echo "none" > $fcur
elif [ -z "$stn" ]; then
	exit
else
	url=$(cat $stationlist | grep -w $stn | cut -d' ' -f2)
	pkill $plyr
	$plyr "$url" &
	echo "$stn" > $fcur
fi
