#!/bin/sh
#
# razz - simple internet radio stream handler 
#

plyr=mpv

# where is the list of streams?
stationlist="$HOME/dotfiles/radio"

# load colour defs
. $HOME/dotfiles/colourdefs

dmenu_cmd="dmenu -fn $fnt -nb $bg -nf $nf -sb $bg -sf $sf"

stn=$(cat $stationlist | cut -d' ' -f1 | sort | $dmenu_cmd)

if [ "$stn" = "stop" ]; then
	pkill $plyr
elif [ -z "$stn"]; then
	exit
else
	url=$(cat $stationlist | grep -w $stn | cut -d' ' -f2)
	pkill $plyr
	$plyr "$url"
fi
