#!/bin/sh
#
# razz - simple internet radio stream handler [ req. dmenu mplayer ]
#

. grabcolours.sh

# where is the list of streams?
stationlist="$HOME/radio"

sw=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
sh=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

w=$sw
h=20
xoff=$((sw/2 - w/2))
yoff=0

dmenu_cmd="dmenu -fn "$fnt" -nb "#$bg" -nf "#$fg" -sb "#$bg" -sf "#$red" -x $xoff -y $yoff -w $w -h $h"

stn=$(cat $stationlist | cut -d' ' -f1 | sort | $dmenu_cmd)

if [ "$stn" = "stop" ]; then
	pkill mplayer
elif [ -z "$stn"]; then
	exit
else
	url=$(cat $stationlist | grep $stn | cut -d' ' -f2)
	pkill mplayer
	mplayer "$url"
fi
