#!/bin/sh

file=$HOME/Pictures/scrot/$(date '+%y%m%d_%H%M').png

scrot ${file}
poppy "scrot saved" &
#notify-send "scrot saved" &

case $1 in
	up) #upload to the null pointer
		curl -s -F"file=@${file}" https://0x0.st | xargs echo -n | xclip 
		poppy "scrot uploaded"
		#notify-send "scrot uploaded"
		;;
esac
