#! /bin/bash
#
# szyslak, a simple bartender 
#

clock() {
    date '+%a %H:%M'
}

battery() {
    bat=$(cat /sys/class/power_supply/BAT1/capacity)
    bats=$(cat /sys/class/power_supply/BAT1/status)
    batbuf=""
    if [ $bat -le 10 ] 
    then
        batbuf="[    ]"
    elif [ $bat -gt 10 ] && [ $bat -le 25 ] 
    then
        batbuf="[#   ]"
    elif [ $bat -gt 25 ] && [ $bat -le 50 ] 
    then
        batbuf="[##  ]"
    elif [ $bat -gt 50 ] && [ $bat -le 75 ] 
    then
        batbuf="[### "]
    elif [ $bat -gt 75 ] && [ $bat -le 100 ] 
    then
        batbuf="[####]"
    fi
    
    if [ $bats == "Full" ] 
    then
        batbuf="=$batbuf="
    elif [ $bats == "Discharging" ] 
    then
        batbuf="-$batbuf-"
    elif [ $bats == "Charging" ] 
    then
        batbuf="+$batbuf+"
    fi

    echo "$batbuf"
    

}

volume() {
    vol=$(amixer -M get Master | awk -F"[][]" '/dB/ { print $2 }')
    echo "$vol"
}

groups() {
    cur=`xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}'`
    tot=`xprop -root _NET_NUMBER_OF_DESKTOPS | awk '{print $3}'`

    #grps=( 一 二 三 四 五 )
    #grps=( I II III IV V )
    #echo ${grps[$cur]}

    for w in `seq 0 $((cur - 1))`; do line="${line}0 "; done
    line="${line}X "
    for w in `seq $((cur + 2)) $tot`; do line="${line}0 "; done
    echo $line
}

wname() {
    xtitle
}

# this is DWM, son!
while :; do
    buf="$(clock) // $(battery)"
    xsetroot -name "$buf"
    sleep 30s
done
