#!/bin/bash

#
# terrapin - snap! (an exercise in scripting bspc calls)
#

sw=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
sh=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

ww=$(xwininfo -id `bspc query -N -n` | grep "Width" | cut -d ':' -f2)
wh=$(xwininfo -id `bspc query -N -n` | grep "Height" | cut -d ':' -f2)

gp=$(bspc config window_gap)
bw=$(bspc config border_width)

case $1 in
    mm)
        dw=$((sw/2 - ww - 2*gp - 2*bw))
        dh=$((sh - wh - 2*gp - 2*bw))
        bspc node -z bottom_right $dw $dh ;;
    tl)
        
esac
